### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by chmodmasx** [1ly4s0/battlylauncher#10]
utilice AppImage, deb o siempre crashea en el mismo lugar, busca actualizaciones -> abre el panel para seleccionar idioma y se cierra.

Salida de terminal:

chmodmasx@chmodmasx-H370M-DS3H:~$ battlylauncher 
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
Checking for update
Update for version 1.7.2 is not available (latest version: 1.7.2, downgrade is disallowed).
node:internal/fs/utils:916
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of TypeError
    at Object.writeFileSync (node:fs:2281:5)
    at process.<anonymous> (/opt/Battly Launcher/resources/app/src/app.js:1:7301)
    at process.emit (node:events:526:35)
    at process._fatalException (node:internal/process/execution:159:25) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.9.0

OS: Linux Mint 21.3
RAM: 24GB
Tipo de disco: SSD
GPU: RTX 2070 8GB

**Comment by 1ly4s0** [comment]
Investigando...

**Comment by 1ly4s0** [comment]
Error solucionado, la solución será actualizar Battly a la última versión [1.7.3]
