### ISSUE TITLE
[BUG] Los botones de CERRAR, MINIMIZAR, MAXIMIZAR. No funcionan en macos

### ISSUE THREAD

**Issue by DiegoDev2** [1ly4s0/battlylauncher#12]
No funcionan en macos, en mi caso no hacen nada.

**Comment by 1ly4s0** [comment]
Fix implementado en #13 . Los cambios se recibirán en la update 2.2.1

**Comment by DiegoDev2** [comment]
> Fix implementado en #13 . Los cambios se recibirán en la update 2.2.1

Esta bien.
