### ISSUE TITLE
[BUG] Error al abrir ModPacks en Battly.

### ISSUE THREAD

**Issue by Catttj** [1ly4s0/battlylauncher#15]
Intente instalar un ModPack, al subir el archivo y darle a instalar, solo se quedo en "Instalando ModPack... Puede tardar un poco..."
Esto sucede desde la version 2.2.0 de Battly, ya varios usuarios han reportado el mismo error en su servidor.

Aqui le dejo una captura del error.
![image](https://github.com/user-attachments/assets/c258e43c-f236-4187-a06c-dec36e77b887)

**Comment by caca123sigmaskibidi** [comment]
Tambien a veces sale que "El modpack no es compatible" (ver imagen adjunta) con los modpacks .zip, usualmente curseforge.
![imagen_2024-10-12_161111441](https://github.com/user-attachments/assets/686d6975-a807-4f20-b1f4-640dcfc21dc6)

**Comment by 1ly4s0** [comment]
Fix implementado en #16  . Los cambios se recibirán en la update 2.2.1.

Solucionado volviendo atrás en la versión de Electron (32.1.2 > 31.7.0), para solucionarlo definitivamente habría que actualizar +30 archivos como dice la [changelog de Electron](https://www.electronjs.org/blog/electron-32-0#breaking-changes)
