### ISSUE TITLE
[BUG] La instalación se cancela cuando hay un problema de internet

### ISSUE THREAD

**Issue by 1ly4s0** [1ly4s0/battlylauncher#17]
Este error consiste en que la descarga de una versión de Minecraft es cancelada cuando la red del usuario se corta o simplemente el sistema corta la descarga por alguna razón.

Para replicar este problema, hay que seguir estos pasos.
1. Abrir Battly
2. Descargar una versión
3. Desconectar el internet a mitad de descarga.

Cuando se hagan estos pasos, saldrá un panel de error informando que ha habido un error al abrir Minecraft y muestra el error. Esto es molesto, ya que algunos usuarios tienen un internet lento y hay que estar reiniciando a cada rato.

![image](https://github.com/user-attachments/assets/0d08df52-70ee-47a5-845c-f2d6cf6e9606)

**Comment by 1ly4s0** [comment]
Solucionado en #18 . Será implementado/solucionado en la siguiente versión de Battly (2.2.1)

## Solcuión temporal
Cerrar y volver a descargar la versión hasta que se complete y asegurarte de que mantienes una conexión a internet estable.

**Comment by bruhhh-xyt** [comment]
Solcuión
