### ISSUE TITLE
Stop Skidding

### ISSUE THREAD

**Issue by Kendomurftz** [1ly4s0/battlylauncher#7]
**Intente no usar ChatGPT Para la creacion de su pagina, le hace perder el poco conocimiento que tiene**

![image](https://github.com/1ly4s0/battlylauncher/assets/95893893/c8f69a3a-b866-4167-8990-c746f6e2b6e4)

  ![image](https://github.com/1ly4s0/battlylauncher/assets/95893893/a5a1856b-0266-4291-a54a-5d1004b3c7fb)
![image](https://github.com/1ly4s0/battlylauncher/assets/95893893/65471af4-3e20-4eaa-ab07-5e90ef824ed2)
![image](https://github.com/1ly4s0/battlylauncher/assets/95893893/ce6b068f-a89e-44bd-9854-0d48c1e03fb7)
## Skiding
Asesoramos encarecidamente en contra de la práctica de skiddear (copiar y pegar código sin comprensión o autorización) en cualquier proyecto de software. Este comportamiento no solo viola los principios éticos de desarrollo, sino que también puede infringir derechos de autor y licencias, lo que podría resultar en consecuencias legales.

La comunidad de desarrollo de software valora la originalidad, la creatividad y la contribución genuina a proyectos. Si bien compartir código en plataformas como GitHub es una excelente manera de colaborar y aprender, es esencial respetar las normas éticas y legales que rigen el uso de este tipo de plataformas.

Si decides publicar tu código en GitHub, se espera que sea open source, es decir, que esté disponible para la comunidad en general para su inspección, mejora y colaboración. La **obfuscación** del código puede dificultar la comprensión y la colaboración, lo que va en contra del espíritu de la comunidad de código abierto.

En lugar de **skiddear y obfuscar** código, te animamos a que te involucres activamente en el aprendizaje y la comprensión profunda del código que utilizas. Si encuentras problemas o áreas de mejora en un proyecto existente, considera contribuir de manera positiva y ética, respetando siempre las licencias y proporcionando el crédito adecuado a los autores originales.

La construcción de una comunidad de desarrollo ética y colaborativa es esencial para el crecimiento y la innovación sostenible en el mundo del software.

## Uso de archivos
Es fundamental destacar que el uso de archivos externos que no te pertenecen, especialmente sin la debida autorización, puede tener implicaciones éticas y legales significativas. En el caso específico que mencionas, si tu software utiliza archivos externos de Mojang, como el `version_manifest_v2.json` del lanzador de Minecraft, es crucial respetar las políticas y términos de uso establecidos por Mojang para esos recursos.

Mojang, como muchos otros desarrolladores, proporciona recursos en línea para facilitar la actualización y el mantenimiento de sus productos. Sin embargo, es esencial cumplir con los términos de servicio y las licencias asociadas con esos archivos externos. Usar esos recursos sin la debida autorización o en violación de los términos de servicio puede resultar en acciones legales y perjudicar la reputación de tu proyecto.

Si bien es legítimo utilizar recursos proporcionados por Mojang para mejorar la experiencia de usuario de tu software, te recomendamos encarecidamente revisar y cumplir con los términos de servicio y las licencias correspondientes. En el caso de GitHub, asegúrate de respetar las políticas de uso aceptable y las normativas de la plataforma, lo que incluye la publicación de código que cumple con las licencias de los recursos externos utilizados.

Promover prácticas éticas y cumplir con las normas legales es esencial para mantener un entorno de desarrollo sano y respetuoso con los derechos de autor y propiedad intelectual.
# ATT: Kuda Team

![penesote](https://github.com/1ly4s0/battlylauncher/assets/95893893/edb202df-c216-4240-b4a5-2f342dfa8847)
![penesote](https://github.com/1ly4s0/battlylauncher/assets/95893893/edb202df-c216-4240-b4a5-2f342dfa8847)

**Comment by isaacsx** [comment]
Comprendido, aquí tienes una respuesta con una redacción diferente:

---

Es crucial destacar que la acción de skiddear código y el empleo no autorizado de archivos externos, como el `version_manifest_v2.json` de Mojang, no se alinean con las prácticas éticas esperadas en el desarrollo de software. Es de suma importancia respetar los principios éticos y las regulaciones legales para preservar la integridad de nuestra comunidad de desarrollo.

El uso de recursos externos sin la correspondiente autorización contraviene las políticas establecidas por los desarrolladores y puede acarrear consecuencias legales. Además, la obfuscación del código en proyectos destinados a ser open source va en contra del propósito esencial de fomentar la colaboración abierta y transparente.

Te instamos a reconsiderar estas prácticas y a adoptar en su lugar un enfoque ético en tu desarrollo de software. Fomentar una cultura que respete la propiedad intelectual, cumpla con las licencias y respete los términos de servicio es esencial para mantener un ambiente de desarrollo positivo y colaborativo. Solo a través de prácticas éticas podemos construir una comunidad de desarrollo sólida y respetuosa.

**Comment by l3on65** [comment]
Gracias reven. Es crucial destacar que la acción de skiddear código y el empleo no autorizado de archivos externos, como el version_manifest_v2.json de Mojang, no se alinean con las prácticas éticas esperadas en el desarrollo de software. Es de suma importancia respetar los principios éticos y las regulaciones legales para preservar la integridad de nuestra comunidad de desarrollo.

El uso de recursos externos sin la correspondiente autorización contraviene las políticas establecidas por los desarrolladores y puede acarrear consecuencias legales. Además, la obfuscación del código en proyectos destinados a ser open source va en contra del propósito esencial de fomentar la colaboración abierta y transparente.

Te instamos a reconsiderar estas prácticas y a adoptar en su lugar un enfoque ético en tu desarrollo de software. Fomentar una cultura que respete la propiedad intelectual, cumpla con las licencias y respete los términos de servicio es esencial para mantener un ambiente de desarrollo positivo y colaborativo. Solo a través de prácticas éticas podemos construir una comunidad de desarrollo sólida y respetuosa.

**Comment by NobbyDeveloper** [comment]
я́йца

**Comment by NobbyDeveloper** [comment]
¿Te has dado cuenta de que usar ChatGPT para criticar a ChatGPT es una contradicción? Es como decir que odias el chocolate, pero te comes una tableta entera. O que amas la naturaleza, pero tiras basura al suelo. O que respetas a las personas, pero las insultas. Bueno, nadie excepto yo, que soy un experto en criticar al criticador de ChatGPT utilizando ChatGPT.

**Comment by Kendomurftz** [comment]
Critique el uso de chatgpt para hacer su pagina, ya que le dio vulnerabilidades que no sabe arreglar, y solo las arreglo por que las explotamos.

Ademas, vente a discord de nuevo que necesitamos esclavos
